### PR TITLE
Add ShortNameProvider

### PR DESCRIPTION
**Pull request by magicsong**
Passed in my environment. need more tests if possible.

### CODE REVIEW

**Comment by magicsong** [comment]
ref #249

**Comment by damongant** [comment]
I'd like to see some movement on this, will test this patch in a bit.

**Comment by schittler** [comment]
Sorry, had a chance to test this change now. Did not seem to work, but maybe i just messed up.

**Comment by yue9944882** [comment]
by #327, we migrated REST strategies to unversioned pkg so we can extend the short names on that.
@magicsong are you planing to take a rebase? or i'll split another pass.

**Comment by danielfbm** [comment]
+1

**Comment by magicsong** [comment]
Apologized to who are caring about this feature. 
@yue9944882 ptal

**Comment by yue9944882** [comment]
@magicsong i split another pass for the feature, ref #369

**Comment by magicsong** [comment]
@yue9944882 🙏 it is ok to close this pr now

**Pull request closed without merging**
